// The six playable warships. Every one of them is also used as an enemy.
// `mounts` place the weapon hardware on the hull; the mesh builder reads the
// same list, so the guns you see are the guns that actually shoot.

export const SHIPS = [
  {
    id: 'groza',
    name: 'RS Grosa',
    klass: 'Schwerer Schlachtkreuzer',
    role: 'Panzerung & Feuerkraft',
    desc: 'Fliegende Festung auf See: dickste Panzerung, schwerste Salven, aber traege wie ein Eisberg.',
    hull: { type: 'battlecruiser', length: 96, beam: 14, draft: 5.2, deck: 4.6 },
    colors: { hull: 0x6b7885, deck: 0x515c67, trim: 0x3d454e, accent: 0xb2402f },
    hp: 5200, armor: 0.72, maxSpeed: 17, accel: 3.4, turnRate: 0.30,
    preferredRange: 1250,
    weapons: ['gun130', 'cruiseMissile', 'ciws'],
    special: { id: 'barrage', name: 'Sperrfeuer', cooldown: 34, duration: 7 },
    mounts: [
      { weapon: 'gun130', type: 'turret', pos: [0, 4.9, 26], scale: 1.25 },
      { weapon: 'gun130', type: 'turret', pos: [0, 6.6, 16], scale: 1.25 },
      { weapon: 'gun130', type: 'turret', pos: [0, 5.0, -30], scale: 1.25, rear: true },
      { weapon: 'cruiseMissile', type: 'vls', pos: [0, 4.6, 5], cells: [4, 3] },
      { weapon: 'ciws', type: 'ciws', pos: [5.2, 7.4, -6] },
      { weapon: 'ciws', type: 'ciws', pos: [-5.2, 7.4, -6] },
    ],
  },
  {
    id: 'vector',
    name: 'USS Vector',
    klass: 'Stealth-Zerstoerer',
    role: 'Praezision & Reichweite',
    desc: 'Facettierter Rumpf, kaum Radarecho. Die Railgun schlaegt auf 2.6 km zu - und geht glatt durch.',
    hull: { type: 'stealth', length: 82, beam: 12, draft: 4.4, deck: 4.0 },
    colors: { hull: 0x525d69, deck: 0x3e4750, trim: 0x2b323a, accent: 0x3fa9d6 },
    hp: 3400, armor: 0.55, maxSpeed: 22, accel: 5.2, turnRate: 0.42,
    preferredRange: 1750,
    weapons: ['railgun', 'guidedMissile', 'ciws'],
    special: { id: 'stealth', name: 'Tarnkappe', cooldown: 30, duration: 6 },
    mounts: [
      { weapon: 'railgun', type: 'turret', pos: [0, 4.4, 22], scale: 1.15, railgun: true },
      { weapon: 'guidedMissile', type: 'vls', pos: [0, 4.2, 2], cells: [3, 3] },
      { weapon: 'ciws', type: 'ciws', pos: [0, 8.2, -14] },
    ],
  },
  {
    id: 'sentinel',
    name: 'HMS Sentinel',
    klass: 'Aegis-Raketenzerstoerer',
    role: 'Allrounder',
    desc: 'Ausgewogen in allem: schnelle 127er, achtfache VLS-Schwarmsalve und ein Notfall-Reparaturteam.',
    hull: { type: 'destroyer', length: 78, beam: 11, draft: 4.2, deck: 4.0 },
    colors: { hull: 0x76828e, deck: 0x5c6772, trim: 0x454e57, accent: 0xd8b23a },
    hp: 3600, armor: 0.58, maxSpeed: 21, accel: 4.8, turnRate: 0.40,
    preferredRange: 1400,
    weapons: ['gun127', 'missileSalvo', 'ciws'],
    special: { id: 'repair', name: 'Schadenskontrolle', cooldown: 38, duration: 6, heal: 1100 },
    mounts: [
      { weapon: 'gun127', type: 'turret', pos: [0, 4.6, 25], scale: 1.0 },
      { weapon: 'missileSalvo', type: 'vls', pos: [0, 4.3, 12], cells: [4, 2] },
      { weapon: 'missileSalvo', type: 'vls', pos: [0, 4.3, -24], cells: [4, 2] },
      { weapon: 'ciws', type: 'ciws', pos: [0, 9.0, 4] },
      { weapon: 'ciws', type: 'ciws', pos: [0, 6.2, -14] },
    ],
  },
  {
    id: 'vipera',
    name: 'FNS Vipera',
    klass: 'Schnellangriffs-Korvette',
    role: 'Tempo & Torpedos',
    desc: 'Winzig, spurtstark, unglaublich wendig. Reisst mit Torpedos Loecher, die kein Kreuzer verzeiht.',
    hull: { type: 'corvette', length: 48, beam: 8, draft: 2.8, deck: 3.0 },
    colors: { hull: 0x5d6b64, deck: 0x48544f, trim: 0x333b38, accent: 0x63d27a },
    hp: 2000, armor: 0.38, maxSpeed: 32, accel: 9.0, turnRate: 0.92,
    preferredRange: 750,
    weapons: ['autocannon', 'torpedo', 'ciws'],
    special: { id: 'boost', name: 'Nachbrenner', cooldown: 18, duration: 5, factor: 1.55 },
    mounts: [
      { weapon: 'autocannon', type: 'turret', pos: [0, 3.4, 15], scale: 0.8 },
      { weapon: 'torpedo', type: 'tube', pos: [3.4, 3.2, -4] },
      { weapon: 'torpedo', type: 'tube', pos: [-3.4, 3.2, -4] },
      { weapon: 'ciws', type: 'ciws', pos: [0, 4.2, -16] },
    ],
  },
  {
    id: 'leviathan',
    name: 'CVN Leviathan',
    klass: 'Flugzeugtraeger',
    role: 'Luftschlag & Ausdauer',
    desc: 'Schwimmender Flugplatz. Schickt Drohnenstaffeln quer ueber die Karte, waehrend Phalanx alles abraeumt.',
    hull: { type: 'carrier', length: 150, beam: 26, draft: 6.5, deck: 7.0 },
    colors: { hull: 0x6d7885, deck: 0x444b52, trim: 0x30363c, accent: 0xe0e5e8 },
    hp: 7400, armor: 0.66, maxSpeed: 14, accel: 2.6, turnRate: 0.17,
    preferredRange: 1900,
    weapons: ['airstrike', 'samBattery', 'ciwsHeavy'],
    special: { id: 'aegis', name: 'Schutzschirm', cooldown: 40, duration: 8 },
    mounts: [
      { weapon: 'airstrike', type: 'deck', pos: [-6, 7.4, 20] },
      { weapon: 'samBattery', type: 'vls', pos: [10.5, 7.2, -46], cells: [2, 3] },
      { weapon: 'samBattery', type: 'vls', pos: [-10.5, 7.2, 52], cells: [2, 3] },
      { weapon: 'ciwsHeavy', type: 'ciws', pos: [10.8, 9.4, 40] },
      { weapon: 'ciwsHeavy', type: 'ciws', pos: [-10.8, 9.4, -40] },
      { weapon: 'ciwsHeavy', type: 'ciws', pos: [11.2, 13.5, -8] },
    ],
  },
  {
    id: 'nerpa',
    name: 'K-431 Nerpa',
    klass: 'Angriffs-U-Boot',
    role: 'Tarnung & Schlagkraft',
    desc: 'Taucht ab, wird unsichtbar fuer Kanonen und schiebt 650-mm-Torpedos in jede Breitseite.',
    hull: { type: 'submarine', length: 84, beam: 10, draft: 4.6, deck: 2.4 },
    colors: { hull: 0x40464c, deck: 0x33383d, trim: 0x22262a, accent: 0xc0392b },
    hp: 2600, armor: 0.46, maxSpeed: 19, accel: 4.4, turnRate: 0.38,
    preferredRange: 900,
    weapons: ['heavyTorpedo', 'cruiseMissile', 'deckgun'],
    special: { id: 'dive', name: 'Tauchgang', cooldown: 6, duration: 0 },
    mounts: [
      { weapon: 'heavyTorpedo', type: 'tube', pos: [2.6, 0.6, 36] },
      { weapon: 'heavyTorpedo', type: 'tube', pos: [-2.6, 0.6, 36] },
      { weapon: 'cruiseMissile', type: 'vls', pos: [0, 2.4, 8], cells: [2, 2] },
      { weapon: 'deckgun', type: 'turret', pos: [0, 2.6, -6], scale: 0.75 },
    ],
  },
];

export const SHIP_BY_ID = Object.fromEntries(SHIPS.map((s) => [s.id, s]));
